global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hh-service'
    static_configs:
      - targets: ['hh-app:8000']

  - job_name: 'sso-service'
    static_configs:
      - targets: ['sso-app:8010']

  - job_name: 'user-searches-service'
    static_configs:
      - targets: ['searches-app:8020']
